import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { type Layout } from "@/types";

const inter = Inter({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Layout) {
	return (
		<html lang="en">
			<body className={`${inter.className} flex h-0 min-h-screen flex-col`}>{children}</body>
		</html>
	);
}
